### ISSUE TITLE
这个xUI是否跟勇哥的warp冲突？【已解决，安装环境问题，一般人不会碰到。哈哈】

### ISSUE THREAD

**Issue by z10056** [kkkyg/x-ui-yg#2]
一开始用内核4.19的 Debian10来安装勇哥的xui和warp 点安装的xui 设置完端口 域名证书什么的之后再安装了warp warp也能正常获取到ip 然后重启一下vps 重启之后发现 warp获取不到ipv4了 怎么弄都没用 除非卸载warp或者重新安装warp并获取ip 
重新安装warp并获取到ip之后 warp脚本显示有ip了 但节点任然无法上网 用 curl ip.gs获取的ip也是warp ip  没办法只能重启 重启之后ip又没了
到这我还以为是内核的问题 
找了一个bbr脚本 升级到了5.15版本的bbrplus
依然是先安装xui 在安装warp 重启之后warp依然丢失ipv4的ip （我选择的是添加虚拟ipv4）
折腾了俩小时 到最后 在内核5.15bbrplus 先安装warp 在安装xui 发现用xui申请证书的时候会关闭warp 是否跟这个有关系呢 麻烦勇哥能回复一下

**Comment by z10056** [comment]
系统架构是kvm 用原版xui跟勇哥的warp不冲突 看了一下勇哥的warp介绍  无须安装WARP的X-UI修改版本  应该可以肯定是xui修改版跟warp冲突了

**Comment by kkkyg** [comment]
是什么vps？为保证显示正确，xui-yg与证书申请都会临时关闭warp后再开启，我试了没问题

**Comment by kkkyg** [comment]
warp安装好后，看下三种情况ip显示
停止systemctl stop wg-quick@wgcf
测ip
启动systemctl start wg-quick@wgcf
测ip
重启vps
测ip

**Comment by z10056** [comment]
> 



> 是什么vps？为保证保证显示，xui-yg与证书在申请安装时简化，我试了没多久

Rn的vps 也就是一年十刀的 
 我是安装完xui跟warp之后 进入xui修改证书 用https进入面板 设置完证书之后 保存 我习惯是重启vps 不是重启面板 重启完之后就发现连不上网了 进vps运行cfwarp 运行结果显示获取不到ipv4 
我试过6 刷奈飞ip跟7关闭打开warp都没用
6是卡在 选择刷warp还是socks那一步 
7则是 没有反应 选择 打开关闭warp都不行 只能选择卸载 或者运行1 2 3重新获取warp ip 
就算是重新获取了ip 在vps里测ip也正常 节点那里仍上不了网 我节点配置是没有问题的

**Comment by kkkyg** [comment]
> > 
> 
> > 是什么vps？为保证保证显示，xui-yg与证书在申请安装时简化，我试了没多久
> 
> Rn的vps 也就是一年十刀的 我是安装完xui跟warp之后 进入xui修改证书 用https进入面板 设置完证书之后 保存 我习惯是重启vps 不是重启面板 重启完之后就发现连不上网了 进vps运行cfwarp 运行结果显示获取不到ipv4 我试过6 刷奈飞ip跟7关闭打开warp都没用 6是卡在 选择刷warp还是socks那一步 7则是 没有反应 选择 打开关闭warp都不行 只能选择卸载 或者运行1 2 3重新获取warp ip 就算是重新获取了ip 在vps里测ip也正常 节点那里仍上不了网 我节点配置是没有问题的

只装WARP。也是这样的问题吗？

**Comment by z10056** [comment]
> > > 是什么vps？为保证保证显示，xui-yg与证书在申请安装时简化，我试了没多久
> > 
> > 
> > Rn的vps 也就是一年十刀的 我是安装完xui跟warp之后 进入xui修改证书 用https进入面板 设置完证书之后 保存 我习惯是重启vps 不是重启面板 重启完之后就发现连不上网了 进vps运行cfwarp 运行结果显示获取不到ipv4 我试过6 刷奈飞ip跟7关闭打开warp都没用 6是卡在 选择刷warp还是socks那一步 7则是 没有反应 选择 打开关闭warp都不行 只能选择卸载 或者运行1 2 3重新获取warp ip 就算是重新获取了ip 在vps里测ip也正常 节点那里仍上不了网 我节点配置是没有问题的
> 
> 只装WARP。也是这样的问题吗？

安装warp跟原版xui是没有问题的  或者只安装warp跟其他v2脚本也没问题
我记得这个 vps重启之后warp获取不到ip好像是早期的bug吧

**Comment by kkkyg** [comment]
> > > > 是什么vps？为保证保证显示，xui-yg与证书在申请安装时简化，我试了没多久
> > > 
> > > 
> > > Rn的vps 也就是一年十刀的 我是安装完xui跟warp之后 进入xui修改证书 用https进入面板 设置完证书之后 保存 我习惯是重启vps 不是重启面板 重启完之后就发现连不上网了 进vps运行cfwarp 运行结果显示获取不到ipv4 我试过6 刷奈飞ip跟7关闭打开warp都没用 6是卡在 选择刷warp还是socks那一步 7则是 没有反应 选择 打开关闭warp都不行 只能选择卸载 或者运行1 2 3重新获取warp ip 就算是重新获取了ip 在vps里测ip也正常 节点那里仍上不了网 我节点配置是没有问题的
> > 
> > 
> > 只装WARP。也是这样的问题吗？
> 
> 安装warp跟原版xui是没有问题的 或者只安装warp跟其他v2脚本也没问题 我记得这个 vps重启之后warp获取不到ip好像是早期的bug吧

在一个干净的环境下重新安装试试

**Comment by z10056** [comment]
> > > > > 是什么vps？为保证保证显示，xui-yg与证书在申请安装时简化，我试了没多久
> > > > 
> > > > 
> > > > Rn的vps 也就是一年十刀的 我是安装完xui跟warp之后 进入xui修改证书 用https进入面板 设置完证书之后 保存 我习惯是重启vps 不是重启面板 重启完之后就发现连不上网了 进vps运行cfwarp 运行结果显示获取不到ipv4 我试过6 刷奈飞ip跟7关闭打开warp都没用 6是卡在 选择刷warp还是socks那一步 7则是 没有反应 选择 打开关闭warp都不行 只能选择卸载 或者运行1 2 3重新获取warp ip 就算是重新获取了ip 在vps里测ip也正常 节点那里仍上不了网 我节点配置是没有问题的
> > > 
> > > 
> > > 只装WARP。也是这样的问题吗？
> > 
> > 
> > 安装warp跟原版xui是没有问题的 或者只安装warp跟其他v2脚本也没问题 我记得这个 vps重启之后warp获取不到ip好像是早期的bug吧
> 
> 在一个干净的环境下重新安装试试，X-UI与WARP没必然关系的。。

所以说我也很懵逼 每次安装都是dd新系统来安装的 现在暂时放弃了 只安装了勇哥的xui 不用warp无非就是有谷歌验证而已

**Comment by z10056** [comment]
> > > > > 是什么vps？为保证保证显示，xui-yg与证书在申请安装时简化，我试了没多久
> > > > 
> > > > 
> > > > Rn的vps 也就是一年十刀的 我是安装完xui跟warp之后 进入xui修改证书 用https进入面板 设置完证书之后 保存 我习惯是重启vps 不是重启面板 重启完之后就发现连不上网了 进vps运行cfwarp 运行结果显示获取不到ipv4 我试过6 刷奈飞ip跟7关闭打开warp都没用 6是卡在 选择刷warp还是socks那一步 7则是 没有反应 选择 打开关闭warp都不行 只能选择卸载 或者运行1 2 3重新获取warp ip 就算是重新获取了ip 在vps里测ip也正常 节点那里仍上不了网 我节点配置是没有问题的
> > > 
> > > 
> > > 只装WARP。也是这样的问题吗？
> > 
> > 
> > 安装warp跟原版xui是没有问题的 或者只安装warp跟其他v2脚本也没问题 我记得这个 vps重启之后warp获取不到ip好像是早期的bug吧
> 
> 在一个干净的环境下重新安装试试，X-UI与WARP没必然关系的。。

勇哥再请教一下 你的博客里说的cf https端口啥意思
举个例子 
我有一个域名 Google.com
现在托管到cf里了 证书是acme申请的 不打开小云朵的情况下 （证书密钥路径都设置完了） 可以通过 https：\\Google.com:54321来访问面板 
现在我打开了小云朵 按照我理解博客图片的 意思 我可以通过 https：\\Google.com:443 来访问面板了？
但我通过https：\\Google.com：443 
https：\\Google.com：2053 
https：\\Google.com：2083都无法访问面板
还是我理解有问题

**Comment by kkkyg** [comment]
> 

https://XX.google.com:443

**Comment by z10056** [comment]
> 格式是https://XX.google.com:443
勇哥 tg私聊你了 tg聊方便
