### ISSUE TITLE
祝你今晚送你妈的灵车撞死你家老小   双喜临门

### ISSUE THREAD

**Issue by coxbrittany** [kkkyg/x-ui-yg#5]
@kkkyg 你妈成盒装的了，还叫呢
# 头发长，你🐴 活的短
# 我他妈踹烂你妈逼你妈还让野狗舔，你说你妈骚不骚，你说你妈逼有多臭
# 你吗那个子宫跟个滑梯似的都挂不住孩子 打个喷嚏就把你这早产儿弄出来了 别逼我给你吗肚脐眼一刀往她子宫里植入55寸液晶大电视  再给你丁丁植入半导体激光设备 远程引爆你吗和你两个栽种 你奶白发人送黑发人
# 你婊子妈子宫被原子弹炸的灰飞烟灭后 竟然出现了一片混沌世界 幸运的是我在你妈子宫里开天辟地了

**Comment by ereed1253** [comment]
@kkkyg 
# 你是把全村茅厕里的稀都吃了吗？嘴那么丑，你🐴不知道？哦，或许你可能没有🐴

**Comment by ereed1253** [comment]
@kkkyg 
# 五行缺日命中欠操的几把玩意

**Comment by ereed1253** [comment]
@kkkyg 
# 小废物你亲妈被野爹叫上几个非洲土著黑加白戳出18个洞野爹还在上面拿小废物的睾丸打高尔夫球呢，没想到小废物们的睾丸一滚进你妈黑屄结果你妈逼迅速扩大就形成了天坑洞穴探险队深入探险呢我操你妈的
