### ISSUE TITLE
嘿兄弟，我看到你🐴了，打开淘宝就看到她在卖逼，标题写着9.9包邮只为拯救脑瘫孩子

### ISSUE THREAD

**Issue by ghost** [kkkyg/x-ui-yg#6]
@kkkyg 
# 你吃你🐴拉的屎，喝你🐴的淫水长大的
# 我刚手滑吉格斯R没放准，放到火葬场，你爹的骨灰当场就变了蘑菇云
# 嘀嘀咕咕啥说话不明不白不清不楚含着你爹批呢
# 你就是你那没吊的爹出芽分化出来的畜生，你个性无能的小屌女人，嘴里吃屎不擦天天冲着别人喷粪，把几把给你拔下来塞你嘴里，你就是一个骚鸡，你那脑子里天天全是水吧，咣当一下他爸的就洪水大爆发，电线杆倒下把你爹电死，我给你爹买坟去你爹坟头慢慢喷屎
# 你爸已经被我挂在迎客松上喜迎八方来客了呢亲亲
# 哦，你爸在天上给你招手呢，你不去安慰一下他。你知道你是怎么来的吗？你爸在过奈何桥的时候看见了你，卖屌的你爸，然后就有了你。往生经超度你全家南无 阿弥多婆夜 哆他伽多夜 哆地夜他 阿弥利都婆毗 阿弥利哆 悉耽婆毗 阿弥唎哆 毗迦兰帝 阿弥唎哆 毗迦兰多 伽弥腻 伽伽那 枳多迦利 莎婆诃
“新你爸屌我护送你亲爹 骨灰的灵车又撞死你一家老小可真是双喜临

**Comment by coxbrittany** [comment]
@kkkyg 
# 🐶咋种，滚去给你死👻跌玛上坟吧，哈哈哈

**Comment by coxbrittany** [comment]
@kkkyg 
# 要么闭上你的嘴，要么藏好你的妈

**Comment by tinashort** [comment]
@kkkyg 
# 你不过是当初我往一条母狗的B里塞了条毛毛虫之后生出来的狗杂种
