### ISSUE TITLE
预先警告

### ISSUE THREAD

**Issue by coxbrittany** [kkkyg/x-ui-yg#9]

**Comment by ereed1253** [comment]
再抄别人的代码就不是两个号炸库怎么简单了，全自动炸你妈的github号

**Comment by ereed1253** [comment]
@kkkyg 
![github_mine](https://user-images.githubusercontent.com/103616231/163299063-395a1273-32a6-4ff2-a01b-3d5456bee80d.jpg)

**Comment by ereed1253** [comment]
@kkkyg
![licence_bs](https://user-images.githubusercontent.com/103616231/163299085-965fe6b9-ab29-48d0-9e59-c4f0322faaee.jpg)

**Comment by coxbrittany** [comment]
贴图包： https://t.me/kkkyg_world
